### ISSUE TITLE
Ruby 2.2.0: private method `load' called for Psych:Module

### ISSUE THREAD

**Issue by simonc** [code-mancers/invoker#133]
Hi, I'm not able to start invoker, I get the following trace:

```
/Users/username/.gem/ruby/2.2.0/gems/invoker-1.3.2/lib/invoker/power/config.rb:40:in `block in load_config': private method `load' called for Psych:Module (NoMethodError)
from /Users/username/.gem/ruby/2.2.0/gems/invoker-1.3.2/lib/invoker/power/config.rb:40:in `open'
from /Users/username/.gem/ruby/2.2.0/gems/invoker-1.3.2/lib/invoker/power/config.rb:40:in `load_config'
from /Users/username/.gem/ruby/2.2.0/gems/invoker-1.3.2/lib/invoker/parsers/config.rb:14:in `initialize'
from /Users/username/.gem/ruby/2.2.0/gems/invoker-1.3.2/lib/invoker.rb:52:in `new'
from /Users/username/.gem/ruby/2.2.0/gems/invoker-1.3.2/lib/invoker.rb:52:in `load_invoker_config'
from /Users/username/.gem/ruby/2.2.0/gems/invoker-1.3.2/lib/invoker/cli.rb:41:in `start'
from /Users/username/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
from /Users/username/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
from /Users/username/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
from /Users/username/.gem/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
from /Users/username/.gem/ruby/2.2.0/gems/invoker-1.3.2/lib/invoker/cli.rb:12:in `start'
from /Users/username/.gem/ruby/2.2.0/gems/invoker-1.3.2/bin/invoker:7:in `<top (required)>'
from /Users/username/.gem/ruby/2.2.0/bin/invoker:23:in `load'
from /Users/username/.gem/ruby/2.2.0/bin/invoker:23:in `<main>'
```

When starting invoker with Ruby 2.2.1 it works properly. Maybe I missed something, a gem version or something else but I can't figure it out.

Thanks! :)

**Comment by simonc** [comment]
Ok, so for future readers. This issue happens when you have several versions of _psych_ installed.
Simply run `gem uninstall psych` an don't reinstall it, it should fix the problem.

**Comment by iffyuva** [comment]
@simonc thanks for updating this issue with solution :)
