### ISSUE TITLE
Process with command powerup_manager exited with status 1

### ISSUE THREAD

**Issue by ProGM** [code-mancers/invoker#184]
I'm on a macOS El Capitan with ruby 2.3.3 (rbenv). After upgrading some dependences in my project, I'm having a strange issue when running `invoker`.

Even if the processes are spawned, I got:
`Process with command powerup_manager exited with status 1`

And the DNS feature is not working. I need to load `localhost:myport` instead of `myproject.dev`

Here's the stack trace:
```
D, [2017-03-04T11:25:12.613585 #28482] DEBUG -- : Terminating 1 actor...
/Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:39:in `check': wrong number of arguments (1 for 0) (ArgumentError)
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:24:in `dispatch'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/invoker-1.5.1/lib/invoker/power/powerup.rb:17:in `block in run'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run_machine'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:194:in `run'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/invoker-1.5.1/lib/invoker/power/powerup.rb:13:in `run'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/invoker-1.5.1/lib/invoker/power/powerup.rb:7:in `block in fork_and_start'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/invoker-1.5.1/lib/invoker/power/powerup.rb:7:in `fork'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/invoker-1.5.1/lib/invoker/power/powerup.rb:7:in `fork_and_start'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/invoker-1.5.1/lib/invoker/process_manager.rb:72:in `run_power_server'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/invoker-1.5.1/lib/invoker/commander.rb:39:in `start_manager'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/invoker-1.5.1/lib/invoker/cli.rb:49:in `start'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/invoker-1.5.1/lib/invoker/cli.rb:12:in `start'
	from /Users/progm/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/invoker-1.5.1/bin/invoker:7:in `<top (required)>'
	from /Users/progm/.rbenv/versions/2.3.3/bin/invoker:22:in `load'
	from /Users/progm/.rbenv/versions/2.3.3/bin/invoker:22:in `<main>'
```

**Comment by WojtekKruszewski** [comment]
@ProGM downgrading ruby to 2.3.1 fixed the problem for me
