### ISSUE TITLE
`distro_installer': Your selected distro is not supported by Invoker

### ISSUE THREAD

**Issue by Krishna-akkala** [code-mancers/invoker#216]
Hi, i am running _**invoker setup --tld testsite**_ from centos7 command prompt, but unfortunately i am facing the below error. 
`/usr/local/share/gems/gems/facter-2.5.1/lib/facter/core/execution/posix.rb:9: warning: Insecure world writable dir /root/.nvm/v9.4.0/bin in PATH, mode 040777
/usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/power/setup/distro/base.rb:35:in `distro_installer': Your selected distro is not supported by Invoker (RuntimeError)
	from /usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/power/setup/linux_setup.rb:59:in `initialize_distro_installer'
	from /usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/power/setup/linux_setup.rb:13:in `setup_invoker'
	from /usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/power/setup.rb:37:in `install'
	from /usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/power/setup.rb:10:in `install'
	from /usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/cli.rb:20:in `setup'
	from /usr/local/share/gems/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/share/gems/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/share/gems/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/share/gems/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/cli.rb:12:in `start'
	from /usr/local/share/gems/gems/invoker-1.5.6/bin/invoker:7:in `<top (required)>'
	from /usr/local/bin/invoker:23:in `load'
	from /usr/local/bin/invoker:23:in `<main>'`

can anyone please help me in resolving this issue?

**Comment by kgrz** [comment]
https://github.com/code-mancers/invoker/blob/efec348d956525db03fa17b51a8d5e1eb56c15da/lib/invoker/power/setup/distro/base.rb#L15 looks like this is the problem. As a short-term fix, I think we can alias the redhat.rb script if os is centos.


We'll see if there's a way to avoid checking OS and switching this and may be setup a more config-based approach for this.
