### ISSUE TITLE
Fresh install fails on Ruby 2.5.1

### ISSUE THREAD

**Issue by iffyuva** [code-mancers/invoker#220]
So, I installed ruby 2.5.1 on osx, and installed invoker. When I run invoker, it errors out:

```
~> invoker start ~/.invoker.ini                                                                                                                                                    ruby-2.5.1
You can enable OSX notification for processes by installing terminal-notifier gem
Traceback (most recent call last):
	18: from /Users/yuva/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
	17: from /Users/yuva/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
	16: from /Users/yuva/.rvm/gems/ruby-2.5.1/bin/invoker:23:in `<main>'
	15: from /Users/yuva/.rvm/gems/ruby-2.5.1/bin/invoker:23:in `load'
	14: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/invoker-1.5.6/bin/invoker:7:in `<top (required)>'
	13: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/invoker-1.5.6/lib/invoker/cli.rb:12:in `start'
	12: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	11: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	10: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 8: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/invoker-1.5.6/lib/invoker/cli.rb:62:in `start'
	 7: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/invoker-1.5.6/lib/invoker/commander.rb:40:in `start_manager'
	 6: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/invoker-1.5.6/lib/invoker/commander.rb:40:in `each'
	 5: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/invoker-1.5.6/lib/invoker/commander.rb:41:in `block in start_manager'
	 4: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/invoker-1.5.6/lib/invoker/process_manager.rb:19:in `start_process'
	 3: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/invoker-1.5.6/lib/invoker/process_manager.rb:189:in `run_command'
	 2: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/invoker-1.5.6/lib/invoker/process_manager.rb:101:in `load_env'
	 1: from /Users/yuva/.rvm/gems/ruby-2.5.1/gems/invoker-1.5.6/lib/invoker/process_manager.rb:101:in `new'
/Users/yuva/.rvm/gems/ruby-2.5.1/gems/dotenv-2.3.0/lib/dotenv/environment.rb:7:in `initialize': wrong number of arguments (given 1, expected 2) (ArgumentError)
```

Any idea whats going on?
/cc @kgrz

**Comment by mathieul** [comment]
The problem comes from the incompatibility with dotenv > 2.2.2, and you have dotenv v2.3.0 installed.

It's been fixed on master: https://github.com/code-mancers/invoker/pull/217

So you can wait until a new version comes out, or you can manually remove dotenv 2.3.0 and install 2.2.2 instead by the mean time.

**Comment by iffyuva** [comment]
@mathieul thanks for pointing it out. :)
